# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import cfzWindow
import core
from cfzWindow.main import Ui_Main
from face_detect.face_detect import detect


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(823, 559)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 170, 431, 331))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 451, 61))
        self.label_2.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(690, 20, 121, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 130, 121, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 240, 121, 61))
        self.pushButton_3.setObjectName("pushButton_3")

        self.Form = Form
        Form.pB = self.pB
        Form.pB2 = self.pB2
        Form.pB3 = self.pB3

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.pB)
        self.pushButton_2.clicked.connect(Form.pB2)
        self.pushButton_3.clicked.connect(Form.pB3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "开始识别"))
        self.pushButton_2.setText(_translate("Form", "确定"))
        self.pushButton_3.setText(_translate("Form", "重试"))


    # 开始识别按钮
    def pB(self):
        print("开始进行人脸识别")
        my_scan_face = detect(name='')  # 建立人脸识别类，此处还需互斥控制，暂时不做考虑
        id = my_scan_face.scan_face(self)  # 得到当前人脸特定的id，0为未识别出已录入的人脸
        if id != 0:
            self.scan_name = my_scan_face.id_dict[id]  # 得到对应id的名字
            print("your namne is :"+self.scan_name)
            self.label_2.setText("欢迎你："+self.scan_name)
        else:
            self.label_2.setText("没找到已注册的用户")
            print("没找到已注册的用户")


    # 确定按钮，进入主界面:
    def pB2(self):
        cfzWindow.id = self.scan_name
        cfzWindow.password = core.database.getPassword()
        cfzWindow.main = QtWidgets.QWidget()
        w_ui = Ui_Main()
        w_ui.setupUi(cfzWindow.main)
        w_ui.label.show()
        cfzWindow.main.show()
        self.Form.close()
        self.father.close()

    # 重试按钮，人脸识别失败时再次进行人脸识别
    def pB3(self):
        self.pB()